version: '3'

networks:
  calcnet:
    driver: bridge

services:
  web:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    networks:
     - calcnet
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: langschool
    volumes:
     - d:/dev/mysql/conf:/etc/mysql/conf.d
     - d:/dev/mysql/data:/var/lib/mysql
    ports:
     - 127.0.0.1:3306:3306
    networks:
     - calcnet
