version: '3'

networks:
  calcnet:
    driver: bridge

services:
  web:
    image: yiisoftware/yii2-php:7.3-apache
    container_name: web
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./data/conf/apache2:/etc/apache2/sites-enabled
    environment:
      - PHP_ENABLE_XDEBUG=1
    ports:
      - '8080:80'
    networks:
     - calcnet
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: langschool
    volumes:
     - ./data/conf/mysql:/etc/mysql/conf.d
     - ./data/db:/var/lib/mysql
    ports:
     - 127.0.0.1:3306:3306
    networks:
     - calcnet
